### ISSUE TITLE
does this work when you don't have a cloudflare enterprise account?

### ISSUE THREAD

**Issue by fool** [chrism2671/netlify-purge-cloudflare-on-deploy#10]
This is a great idea and use case for a plugin, thank you for writing it!  

I work on the Netlify tech support team and was wondering if it works for non-enterprise Cloudflare accounts?    I'm not a customer, but keying off this line:

> The Cloudflare UI and API both prohibit setting Browser Cache TTL to 0 for non-Enterprise domains.

in [their docs](https://support.cloudflare.com/hc/en-us/articles/200168276), I had assumed it was impossible to affect the caching below some timeout (>0 seconds), but maybe "single purge" is handled differently than "setting it to be permanently off"?  Do you have any insight as to whether this can be used at all Cloudflare account levels?

cc @bhavana-netlify @ameerbadri @rsedighi who brought this awesome work to my attention!

PS:  our team are working on a true "post deploy" hook for plugins to use which will be a better trigger for this plugin to use soon :)

**Comment by chrism2671** [comment]
Hi @fool ! Thanks for the kind words! :) We've already met on the community forum, nice to see you here too! :)

Yes, it works for all accounts. This plugin has the effect of pushing the 'purge cache' button that's available inside Cloudflare for all accounts. It doesn't affect the TTL settings for the account.

I agree, the post deploy would be better!

**Comment by fool** [comment]
Yup - I really like working with you and not just because you're nice and paying us, but also because it's always fun to see another "Chris M" :D

Thanks for letting me know about those details!  I think it would make sense for our  to link your plugin from this post - it doesn't change the impact to analytics or A/B testing or certificates, but it at least does "something" around making deploys more atomic which is the most "table stakes" of those features that **everyone** will use.

https://community.netlify.com/t/support-guide-why-isn-t-my-ssl-certificate-provisioning-automatically-with-cloudflare-netlify-are-there-other-problems-with-using-cloudflare-in-front-of-netlify/138

Any concerns or countersuggestions before I edit that post to mention your plugin?

**Comment by chrism2671** [comment]
I definitely think it's worth mentioning. It helps to make deploys atomic - we publish several times a day, and waiting 2 hours TTL for CF to invalidate the cache is way too long. 

I think there are probably people out their with good business reasons for keeping Cloudflare in their stack, so hopefully this can be a step closer to making Netlify & Cloudflare sing together.

On a separate topic, we noticed degradation in performance using Netlify's CDN vs Cloudflare (with Argo). I'd be happy to set up a more detailed performance test if it will help iron out any issues.

**Comment by fool** [comment]
wow, I had no idea the default TTL was 2 hours (I think that's what you're saying?).  We set cache-control headers on our content that specify no caching (or rather, cache-but-check-on-reload), so that's a pretty big gap!

Totally appreciate the effort!

Re: performance, I think you have access to our helpdesk (support@netlify.com) - drop the team a line there and say "hey fool said over in this github issue to escalate to him" and we'll dig in!
