### ISSUE TITLE
Make inputs optional

### ISSUE THREAD

**Issue by ehmicky** [chrism2671/netlify-purge-cloudflare-on-deploy#2]
The preferred way to install Build plugins is via a single click in the Netlify UI.
To enter inputs, users must instead add those to their `netlify.toml` and `package.json`, which involves more work for users.

Would it be possible to provide a default value for some of the inputs? I understand this might not be possible for some inputs though.
  
More information is available [here](https://github.com/netlify/plugins/blob/master/docs/guidelines.md#provide-a-zero-config-default).

**Comment by chrism2671** [comment]
This isn't really an option; this plugin requires Cloudflare credentials without which it cannot function.

**Comment by ehmicky** [comment]
Makes sense.
Is there some way to guess the `zoneId` from the two other inputs?

**Comment by chrism2671** [comment]
Alas no; it's the unique identifier for the site on Cloudflare.

**Comment by ehmicky** [comment]
Thanks! No problem then :)
