### ISSUE TITLE
Confidential inputs should be environment variables

### ISSUE THREAD

**Issue by ehmicky** [chrism2671/netlify-purge-cloudflare-on-deploy#3]
Inputs must be written in the `netlify.toml`. For confidential values, environment variables are more secure since they are edited in the Netlify app, so cannot be accidentally committed and leaked in a public repository.

It seems to me `cloudflareEmail` and `cloudflareApiKey` are confidential information. The `zoneId` might be fine, although it could also be considered confidential. Would it be possible to provide those as environment variables instead of `inputs`? What do you think?

**Comment by chrism2671** [comment]
I certainly can, but would that complicate installation/configuration? I had anticipated that inputs would be shown in the Netlify UI, but I wasn't able to test it.

Happy to reimplement it any way you see fit.

**Comment by ehmicky** [comment]
At the moment, inputs are not shown in the UI, only in `netlify.toml`. If the `netlify.toml` is committed to a public repository by mistake, this would leak the user's Cloudflare credentials.

An alternative to using only environment variable would be to use inputs, with a fallback on environment variables. The `README` should probably then warn that credentials should only be written in the `netlify.toml` for private repositories, and that environment variables are usually more secure.

What do you think?

**Comment by erezrokah** [comment]
I think we should not encourage putting secrets in `netlify.toml`
Since this plugins requires installation via `netlify.toml` I don't see a reason not to include an additional step in the readme to add env variables in Netlify site settings.
For more context see https://github.com/netlify/plugins/blob/master/docs/guidelines.md#provide-a-zero-config-default

**Comment by chrism2671** [comment]
I've moved it exclusively to environment variables - what do you think?

**Comment by ehmicky** [comment]
Thanks @chrism2671!

Would it be possible to throw errors using `utils.build.failBuild()` when one of those required environment variables is missing? Like this, when users install the plugin through the Netlify app the first time (in which case they most likely have not added the environment variables yet), they will see in their build logs which action to take next. :)

**Comment by chrism2671** [comment]
Added! I haven't been able to test that function, but I think it's right.

**Comment by ehmicky** [comment]
Thanks! This looks good.

However, I think there is some syntax error:

```js
  onPreBuild: ({utils}) =>
    if(!CLOUDFLARE_API_KEY || !CLOUDFLARE_ZONE_ID || !CLOUDFLARE_EMAIL) {
      return utils.build.failBuild('You need to add CLOUDFLARE_API_KEY, CLOUDFLARE_ZONE_ID and CLOUDFLARE_EMAIL to your Netlify environment variables.') 
    }
  }
  async onEnd({
```

There is a missing `{` and `,`:

```js
  onPreBuild: ({utils}) => {
    if(!CLOUDFLARE_API_KEY || !CLOUDFLARE_ZONE_ID || !CLOUDFLARE_EMAIL) {
      return utils.build.failBuild('You need to add CLOUDFLARE_API_KEY, CLOUDFLARE_ZONE_ID and CLOUDFLARE_EMAIL to your Netlify environment variables.') 
    }
  },
  async onEnd({
```

**Comment by chrism2671** [comment]
Oops! Fixed!

**Comment by ehmicky** [comment]
Thanks!
