### ISSUE TITLE
What API key scopes does the plugin require?

### ISSUE THREAD

**Issue by Booligoosh** [chrism2671/netlify-purge-cloudflare-on-deploy#7]
Hi, I tried using this plugin, and gave my API key the following scopes:
![image](https://user-images.githubusercontent.com/14034891/85120500-a7cf2400-b266-11ea-92c8-06704932a89a.png)
However, it is giving me a "bad request" error when I use it. Are these the only permissions required for the key?

**Comment by chrism2671** [comment]
Hi Ethan,

I haven't tested it with API scopes (I used global keys); have you tried using an unscoped key?

**Comment by la-mar** [comment]
I can confirm the build doesn't work with the token permissions indicated in the readme.  My token permissions were configured the same as @Booligoosh.  I verified the environment variable configuration multiple times.  The build log is below, though it isn't that informative.


>9:14:36 AM: ❯ Loading plugins
9:14:36 AM:    - netlify-purge-cloudflare-on-deploy@1.0.7 from Netlify app
9:14:36 AM: ​
9:14:36 AM: ┌───────────────────────────────────────────────────────────────┐
9:14:36 AM: │ 1. onPreBuild command from netlify-purge-cloudflare-on-deploy │
9:14:36 AM: └───────────────────────────────────────────────────────────────┘
9:14:36 AM: ​
9:14:36 AM: ​
9:14:36 AM: ┌──────────────────────────────────────────────────────────┐
9:14:36 AM: │ 2. onEnd command from netlify-purge-cloudflare-on-deploy │
9:14:36 AM: └──────────────────────────────────────────────────────────┘
9:14:36 AM: ​
9:14:36 AM: Preparing to trigger Cloudflare cache purge
9:14:37 AM: ​
9:14:37 AM: ┌────────────────────────────────────────────────────┐
9:14:37 AM: │ Plugin "netlify-purge-cloudflare-on-deploy" failed │
9:14:37 AM: └────────────────────────────────────────────────────┘
9:14:37 AM: ​
9:14:37 AM:   Error message
9:14:37 AM:   Error: Cloudflare cache purge failed
9:14:37 AM:   Cloudflare cache couldn't be purged. Status: Bad Request
​
9:14:37 AM:   Plugin details
9:14:37 AM:   Package:        netlify-purge-cloudflare-on-deploy
9:14:37 AM:   Version:        1.0.7
9:14:37 AM:   Repository:     git+https://github.com/chrism2671/netlify-purge-cloudflare-on-deploy.git
9:14:37 AM:   npm link:       https://www.npmjs.com/package/netlify-purge-cloudflare-on-deploy
9:14:37 AM:   Report issues:  https://github.com/chrism2671/netlify-purge-cloudflare-on-deploy/issues
9:14:37 AM: ​
9:14:37 AM:   Error location
9:14:37 AM:   In "onEnd" event in "netlify-purge-cloudflare-on-deploy" from Netlify app
9:14:37 AM:       at onEnd (/opt/buildhome/.netlify-build-plugins/node_modules/netlify-purge-cloudflare-on-deploy/index.js:38:16)
9:14:37 AM: ​
9:14:37 AM:   Resolved config
9:14:37 AM:   build:
9:14:37 AM:     command: npm run export
9:14:37 AM:     commandOrigin: config
9:14:37 AM:     environment:
9:14:37 AM:       - CLOUDFLARE_API_TOKEN
9:14:37 AM:       - CLOUDFLARE_ZONE_ID
9:14:37 AM:     publish: /opt/build/repo/out
9:14:37 AM:   plugins:
9:14:37 AM:     - inputs: {}
9:14:37 AM:       origin: ui
9:14:37 AM:       package: netlify-purge-cloudflare-on-deploy



The plugin worked as expected when I tried it with the global API key.  Seems like the token is just missing a permission or two.

**Comment by chrism2671** [comment]
Thanks for the report! There has been a new build (v1.1); I believe we're just waiting for Netlify to approve it. You can try installing that directly from npm or Github. (I didn't author v1.1 but I think it addresses this issue).
